### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rgbkrk** [nteract/hydrogen#158]
To all collaborators, :tada: welcome to the nteract party! :tada: @willwhitney has transferred ownership of hydrogen to the collective code constructors of nteract.

We've got a lot of packages within the nteract org that are being used to [build a new version of the notebook](https://github.com/nteract/nteract). These same packages can and should be used by Hydrogen. In order to get there, we're going to want to make some targeted refactorings, namely:

* [ ] switching to async by default where possible
      * [ ] use promises
      * [ ] use observables
      * [ ] use [enchannel-zmq-backend](https://github.com/nteract/enchannel-zmq-backend) for the kernel messaging
* [ ] pure javascript, no reliance on jupyter tooling 
* [ ] only protocols, formats, and paths - we want it to work by installing straight from Atom and never have to tell people to run `atom .` from the terminal again
* [x] use [jmp](https://github.com/n-riesco/jmp) for the kernel messaging (@n-riesco working on this point)
* [ ] rely on other npm packages within nteract (or elsewhere) to reduce code duplication and keep things as simple as possible
* [ ] write tests and aim for stability

/cc @jdfreder

**Comment by willwhitney** [comment]
This is going to be such a good place for Hydrogen. I haven't had the time to put in on maintaining the project, let alone adding features, and all of you nteract folks are so talented and so much better focused on this than I am.

I'll still be around from time to time, but I'm really excited to have Hydrogen in good hands from day to day.

**Comment by willwhitney** [comment]
re: using jmp, there's a branch that's basically functional. It will take a minimal refactor to merge.

**Comment by n-riesco** [comment]
I'm interested in translating KernelManager to ES6.

As a first step, I've moved some of the code in `main.coffee` to `kernel-manager.coffee` (see PR #187 ).

**Comment by rgbkrk** [comment]
We've got `zmq-prebuilt` working for 64-bit OS X and Linux (as well as some portion of Windows) if we want to start using that. Those who aren't able to use the prebuilt will end up letting the normal build run. Worth testing:

* https://github.com/nteract/zmq-prebuilt
* https://github.com/rgbkrk/zmq-prebuilt-example

**Comment by slavaGanzin** [comment]
@n-riesco
> I'm interested in translating KernelManager to ES6.

I'll veto this. It just kill simplicity and regard you with nothing.

Why all of you need that ES6? Do you want additional deps as babel and fight with their codebase? They constantly forget to manage dependecies and I couple of times couldn't run a project because all that monstrous deps tree can't be satisfied. And of course you need build system - gulp written by guys thinking they need four different ```sed```implementations for different purposes (because they can) or grunt that (prey the gods) are dying.

ES6 is another pile of syntax sugar as CoffeeScript, except that Coffee is new language built for simplicity and ES6 is the same old JS with all theirs cludges, "but we have destructuring assigment" and a new mindfuckingly stupid static import that they stole from python.
Oh God, I forgot my favorite:
```
x => x //ok
=> {}     //fails
() => x     //fails
() => {} //ok
(x) => x //ok
(x) => x; x //fails
(x) => x; return x //fails
(x) => {x; return x}
```
And don't say it's easy to understand "why". Because it really easy: guys who accept this write academical papers and not hotfixing dramatically fallen server.

That was emotions (I had quit from ES6 project recently). And now clear points:
1. Two language codebase is hard to maintain
2. Newcomers should learn two languages. 
3. Migration wouldn't be acomplished in near future and will finish with something like this: https://github.com/danielbrodin/atom-project-manager. It's aggravated with very bad knowledge of es6 by author.
4. Babel is worst project I ever see. I don't need 13mb of hardly mainteined something that replace ```let a = '1'``` to ```var a = "1"```. Even setup of babel6 is tricky.
5. Now we don't need build system
6. All that --harmony is tricky too. And it doesn't work on Ubuntu LTS...

**Comment by rgbkrk** [comment]
It's hard for me to understand what's wrong with the ok and fails there, likely because I understand the syntax very clearly for ES6. Now, I put it on my wishlist because I personally have noted better participation within JS code bases over coffeescript code bases. JavaScript is the language that offends equally. We don't even have to use Babel though, we can use the current day version of ES5 and ES6 that Atom supports.

I digress. We can always keep this as coffeescript and if people are so inclined, they can make additional packages that encapsulate Hydrogen pieces separately, tested, and exporting commonjs.

**Comment by rgbkrk** [comment]
What I should do know is acknowledge how you're feeling about this @slavaGanzin. You're strongly opposed to ES6, want to carry on with CoffeeScript. This should be a fun project for you and others to work on. As long as you're still submitting PRs and merging others' PRs, we're moving along together.

Even if we disagree, the consensus is in the current code base. What would you like to see us do moving forward @slavaGanzin?

**Comment by slavaGanzin** [comment]
@rgbkrk 
I'm not strongly opposed to ES6, I'm strongly opposed to bilanguage projects and changing languages because we can. If hydrogen had been written in es5 I wouldn't even imagine to migrate to coffeescript.

> "and ES6 that Atom supports."

 And here where it bites: I can't use "es6" I should use es6 that atom supports.

 I personally have noted better participation within Go code bases, should I rewrite couple thousands LOC to achive the same we have now?

**Comment by rgbkrk** [comment]
> And here where it bites: I can't use "es6" I should use "es6 that atom supports".

You seemed very opposed to using Babel, I offered an alternative that would require no build steps. I'm not stating it as the only way, primarily seeking feedback.

Seems like there's a hard stance on sticking with CoffeeScript. I'll remove my anecdote way above and we can continue the conversation in a positive direction.

**Comment by n-riesco** [comment]
@slavaGanzin OK, I'll keep my contributions in Coffeescript.

**Comment by n-riesco** [comment]
Just to let everyone know, I'm planning to work on:

* use [jmp](https://github.com/n-riesco/jmp) / [enchannel-zmq-backend](https://github.com/nteract/enchannel-zmq-backend) for the kernel messaging

**Comment by n-riesco** [comment]
I've updated the list of goals and moved the use of `enchannel-zmq-backend` under the section for switching to async.

**Comment by n-riesco** [comment]
Hi everyone, I've moved this issue to a [wiki page](https://github.com/nteract/hydrogen/wiki/Roadmap).

I would like to use it as a means to tell us each other what we are working on.

@lgeiger, I know you looked into using `transformime`. I'm interested in giving it another go (it would help me simplify and reduce the code in `kernel.coffee`).

**Comment by rgbkrk** [comment]
That's great! Thanks @n-riesco. I'll close this issue.

**Comment by lgeiger** [comment]
Great!
