### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#657]
The [old roadmap](https://github.com/nteract/hydrogen/wiki/Roadmap) is due for an update:

# Roadmap 🚀 

## Short term 🔜 

- [x] Fix issues left from MozSprint. Great for first time contributors: #828

Our documentation is due to a overhaul:
- [x] Add Hydrogen section to the nteract.io website: https://github.com/nteract/nteract.io/pull/7
Preview: https://nteractio-tssddztkpz.now.sh/atom
- [x] Add more content to the nteract.io website: https://github.com/nteract/nteract.io/pull/7 
- [x] Improve our README structure: #654
- [x] Add a Contributor Guide #653 
- [ ] Create a new to programming section #702

## Medium term

Since #627 there've been a lot of refactoring throughout the code base in order to ultimately rely on more nteract component and to make Hydrogen more maintainable and easier to test.
To get there, we're going to want to make some targeted refactorings, namely:

- [x] In continuation of #655 we should refactor the following as real react components:
  - [x] Result View probably powered by [`@nteract/display-area`](https://github.com/nteract/nteract/tree/master/packages/display-area)
    - [x] Spinner component
    - [x] Component for inline result
    - [x] Component for multiline result
    - [x] Component for rich output (I think we could even remove it and use the multiline output for simplicity and to have a more consistent appearance)
  - [x] Watch Sidebar
    - [x] Watch View component
- [x] Refactor List Views to use [atom-select-list](https://github.com/atom/atom-select-list) instead of the deprecated atom-space-pen-views which relies on jQuery. This will reduce the package size by about 2 MB @BenRussert 
- [ ] Reduce size of `main.js` since after the above everything should be a lot more modular
- [ ] Once [kernelspecs](https://github.com/nteract/kernelspecs) can detect the default python installation we should switch to it for kernel detection. This would remove `jupyter` as an external dependency and make kernel detection faster.

## Long term

I would love to switch to [enchannel-zmq](https://github.com/nteract/enchannel-zmq-backend) and [rx-jupyter](https://github.com/nteract/rx-jupyter) for kernel messaging

## Ongoing efforts

Hydrogen is quite stable but still largely untested. In continuation of #650, #648, #656:
- Add more tests (will become easier once more of the above points are completed)
- Add more flow types

Any help is greatly appreciated and needed! Feel free to edit or comment on this issue and claim bullet points or ask questions 😄 🎉

**Comment by BenRussert** [comment]
> Refactor List Views to use atom-select-list instead of the deprecated atom-space-pen-views which relies on jQuery.

I started messing around with this last night, hoping to have some WIP this week. I was starting with watch picker to avoid conflict with #722.

**Comment by lgeiger** [comment]
@BenRussert Very cool! Checkout https://github.com/atom/atom/issues/13254 if you need a real world example on how they did it in Atom itself.

**Comment by lgeiger** [comment]
Hear are some ideas I think would be awesome to explore:

## Ideas
### Make use of Atom's new [docks API](http://blog.atom.io/2017/04/12/atom-1-16.html)
Atom 1.17 beta introduced a a new docks API. I think we could use this to make our panels more flexible:
- [ ] Inspector
- [ ] Watch sidebar

#### Possible new panels:
- External output display similar to http://junolab.org/
- Rich jupyter console connected to the running kernel. Maybe we could make use of [`atom-ink`](https://github.com/JunoLab/atom-ink/):
![](https://raw.githubusercontent.com/JunoLab/atom-ink/master/demos/console.gif)

**Comment by willingc** [comment]
Nice! I really like the output display with junolab.

**Comment by liavassif** [comment]
A separate (single and combined) output display would be great.

**Comment by Announcement** [comment]
Friendly reminder that neither etch nor ink have good docs yet... unless anyone can point me in the right direction. I just simply couldn't figure them out :'(

**Comment by rgbkrk** [comment]
@kolya-ay There is no plan to switch from using React, we want to use common components across various projects in nteract (and :soon: jupyter)

**Comment by Announcement** [comment]
@rgbkrk @kolya-ay For the time being it is not actually viable to switch over, but as soon as they provide documentation expect I'd recommend at least accepting pull requests for the conversion process.

**Comment by rgbkrk** [comment]
The [GitHub / Git integration in Atom uses React](https://github.com/atom/github/blob/74323775a661572d226cad1a777185d95c28eb5b/package.json#L64-L65) instead of etch so I think we can probably assume React is perfectly alright in Atom land.
