### ISSUE TITLE
Mozilla's Global Sprint (June 1st and 2nd 2017)

### ISSUE THREAD

**Issue by lgeiger** [nteract/hydrogen#828]
# Hydrogen participates in [Mozilla’s Global Sprint](https://mozilla.github.io/global-sprint/)

Mozilla’s Global Sprint is a fun, fast-paced and two-day collaborative event to hack and build projects for a healthy Internet. A diverse network of scientists, educators, artists, engineers and others come together in person and online to innovate in the open. [Get your tickets now!](https://mozilla.github.io/global-sprint/register/)

**Join us at https://slackin-nteract.now.sh/**

### No javascript knowledge required:
- Spread the word! Tweet about Hydrogen (https://twitter.com/nteractio), write a blog post or recommend it to your friends.
- Audit our Documentation #827
- Create a new to programming section #702
- Add more examples on how to use Hydrogen #787

### Some JavaScript knowledge required:
- [x] Improve test coverage #813
- [x] Add button to copy from external output area #845
- [x] Create ipynb notebook file from Hydrogen #801
- [x] Hide unnecessary buttons in result view #796 
- [x] Auto scroll result view #774
- [x] Hide open in editor button #797
- [x] Make use of all available space in external output area #833
- [x] Display nice empty message in external display area. #834
